{% set name = "napari-cell-centroid-annotator" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-cell-centroid-annotator-{{ version }}.tar.gz
  sha256: 75fbfad6af0dccc3c071b829a4feae5d5f4a18f54d929dd74cac4cd2b2baf75b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:

    - magicgui
    - napari
    - napari-layer-table
    - napari-plugin-engine
    - numpy
    - pandas
    - python >=3.8
    - qtpy
    - tifffile

test:
  imports:
    - napari_cell_centroid_annotator
  commands:
    - pip list
    # - pip check  # Fails due to pathlib
  requires:
    - pip

about:
  home: https://github.com/tim-vdl/napari-cell-centroid-annotator
  summary: A simple plugin to annotate cell centroids in 3D images
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
